---
# cord-automation-playbook.yml
# Installs the automation scripts used by MaaS to provision nodes.

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "vars/{{ cord_profile }}.yml"
        - vars/local_vars.yml

- name: Set up Automated Compute Node Provisioning
  hosts: head
  roles:
    - { role: automation-integration, when: on_maas }

- name: Prologue
  hosts: head
  roles:
    - head-prologue
