---
# onboard-exampleservice.yml
# Adds the exampleservice to the currently running pod

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "vars/{{ cord_profile }}.yml"
        - vars/local_vars.yml

- name: Create exampleservice config
  hosts: head
  roles:
    - exampleservice-config

- include: add-bootstrap-containers-playbook.yml

- name: Onboard XOS services
  hosts: xos_bootstrap_ui
  connection: docker
  roles:
    - exampleservice-onboard

- include: add-onboard-containers-playbook.yml

- name: Check to see if XOS UI is ready
  hosts: xos_ui
  connection: docker
  roles:
    - xos-ready

