---
# xos-start/tasks/main.yml

- name: Run service-profile Makefile targets for this configuration
  command: ansible xos-1 -u ubuntu -m shell \
    -a "bash -c \"set -o pipefail; cd {{ service_profile_repo_dest }}/{{ xos_configuration }}; make {{ item }} |& tee xos-make-{{ item }}.out\""
  with_items: "{{ xos_config_targets }}"
  tags:
    - skip_ansible_lint

