---
# xos-config/tasks/main.yml

- name: Configure XOS with profile specific TOSCA
  command: "python /opt/xos/tosca/run.py {{ xos_admin_user }} /opt/cord_profile/{{ item }}"
  with_items: "{{ xos_tosca_config_templates }}"
  tags:
    - skip_ansible_lint # TOSCA loading should be idempotent

